name: MADAN_123
version: 1.0.0
config-version: 2
profile: MADAN_123
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  MADAN_123:
    +materialized: view
